<?php

$title = '我的Posts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<!-- blog是路由的名称 -->
    <a href="<?php echo $this->url('blog', array('action'=>'add'));?>">Add new post</a>
</p>

<table class="table">
<tr>
    <th>id</th>
    <th>title</th>
    <th>content</th>
    <th>addtime</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($posts as $post) : ?>
<tr>
    <td><?php echo $this->escapeHtml($post->title);?></td>
    <td><?php echo $this->escapeHtml($post->content);?></td>
    <td><?php echo $this->escapeHtml($post->addtime);?></td>
    <td>
        <a href="<?php echo $this->url('blog',
            array('action'=>'edit', 'id' => $post->id));?>">Edit</a>
        <a href="<?php echo $this->url('blog',
            array('action'=>'delete', 'id' => $post->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
